# -*- coding: utf-8 -*-
"""task1_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PtiErKtPnaDVZ6HtPPKQwMFvtwQUlhF1
"""

import requests
import time
import json
import os
from datetime import datetime

# Base URLs
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# Header (as required)
headers = {"User-Agent": "TrendPulse/1.0"}

# Category keywords
CATEGORIES = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

# Max stories per category
MAX_PER_CATEGORY = 30


def fetch_top_story_ids(limit=500):
    """Fetch top story IDs from HackerNews"""
    try:
        response = requests.get(TOP_STORIES_URL, headers=headers)
        response.raise_for_status()
        return response.json()[:limit]
    except Exception as e:
        print(f"Error fetching top stories: {e}")
        return []


def fetch_story(story_id):
    """Fetch a single story's details"""
    try:
        url = ITEM_URL.format(story_id)
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        print(f"Failed to fetch story {story_id}: {e}")
        return None


def categorize_title(title):
    """Assign category based on keywords"""
    if not title:
        return None

    title_lower = title.lower()

    for category, keywords in CATEGORIES.items():
        for keyword in keywords:
            if keyword in title_lower:
                return category

    return None  # Ignore if no category matched


def main():
    # Step 1: Fetch IDs
    story_ids = fetch_top_story_ids()

    collected_data = []
    category_counts = {cat: 0 for cat in CATEGORIES}

    # Step 2: Loop through categories
    for category in CATEGORIES:
        print(f"Collecting {category} stories...")

        for story_id in story_ids:
            # Stop if we already have enough for this category
            if category_counts[category] >= MAX_PER_CATEGORY:
                break

            story = fetch_story(story_id)

            if not story or "title" not in story:
                continue

            assigned_category = categorize_title(story["title"])

            # Only take stories that match current category
            if assigned_category != category:
                continue

            # Extract required fields
            record = {
                "post_id": story.get("id"),
                "title": story.get("title"),
                "category": assigned_category,
                "score": story.get("score", 0),
                "num_comments": story.get("descendants", 0),
                "author": story.get("by"),
                "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            }

            collected_data.append(record)
            category_counts[category] += 1

        # Sleep AFTER each category (as required)
        time.sleep(2)

    # Step 3: Save to JSON
    if not os.path.exists("data"):
        os.makedirs("data")

    filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

    with open(filename, "w", encoding="utf-8") as f:
        json.dump(collected_data, f, indent=4)

    print(f"Collected {len(collected_data)} stories. Saved to {filename}")


if __name__ == "__main__":
    main()

import json
import os
from datetime import datetime

# Construct the filename based on the current date, similar to the main script
filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

# Check if the file exists before attempting to read it
if os.path.exists(filename):
    with open(filename, "r", encoding="utf-8") as f:
        collected_data = json.load(f)
    print(f"Successfully loaded data from {filename}")
    print(f"Total stories collected: {len(collected_data)}")
    if len(collected_data) >= 100:
        print("Requirement met: At least 100 stories were collected.")
    else:
        print("Warning: Fewer than 100 stories were collected.")
else:
    print(f"Error: File not found at {filename}. Please ensure the previous script ran successfully.")